-- ============================================================
-- MyComicBrain — esquema inicial v1
-- ============================================================

-- publishers
CREATE TABLE IF NOT EXISTS publishers (
    publisher_id    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text        NOT NULL UNIQUE,
    publisher_group text        NOT NULL CHECK (publisher_group IN ('DC', 'MARVEL', 'OTROS'))
);

-- series (no se poda nunca)
CREATE TABLE IF NOT EXISTS series (
    series_id       bigint      PRIMARY KEY,
    name            text        NOT NULL,
    publisher_id    bigint      NOT NULL REFERENCES publishers(publisher_id),
    source          text        NOT NULL DEFAULT 'locg' CHECK (source IN ('locg', 'manual'))
);

-- releases (ventana ±3 meses; el worker la reescribe y poda)
CREATE TABLE IF NOT EXISTS releases (
    issue_id        bigint      PRIMARY KEY,
    series_id       bigint      NOT NULL REFERENCES series(series_id),
    issue_number    text        NOT NULL,
    release_date    date        NOT NULL,
    cover_url       text,
    price           text,
    description     text,
    synced_at       timestamptz NOT NULL DEFAULT now()
);

-- pulls (autosuficiente y duradera)
CREATE TABLE IF NOT EXISTS pulls (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid        NOT NULL REFERENCES auth.users(id),
    series_id       bigint      NOT NULL REFERENCES series(series_id),
    issue_id        bigint,
    issue_number    text        NOT NULL,
    release_date    date        NOT NULL,
    cover_url       text,
    format          text        NOT NULL CHECK (format IN ('fisico', 'digital')),
    status          text        NOT NULL CHECK (status IN ('no_salido', 'descargar', 'listo', 'leido', 'pedido')),
    reading_order   int,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, series_id, issue_number)
);

-- sync_log
CREATE TABLE IF NOT EXISTS sync_log (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    ran_at              timestamptz NOT NULL DEFAULT now(),
    status              text        NOT NULL CHECK (status IN ('ok', 'error')),
    message             text,
    releases_upserted   int
);

-- ── Trigger updated_at en pulls ──────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pulls_updated_at
    BEFORE UPDATE ON pulls
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ── Row Level Security ───────────────────────────────────────
ALTER TABLE publishers  ENABLE ROW LEVEL SECURITY;
ALTER TABLE series      ENABLE ROW LEVEL SECURITY;
ALTER TABLE releases    ENABLE ROW LEVEL SECURITY;
ALTER TABLE pulls       ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_log    ENABLE ROW LEVEL SECURITY;

-- Catálogo: cualquier usuario autenticado puede leer
CREATE POLICY "publishers_read"  ON publishers  FOR SELECT TO authenticated USING (true);
CREATE POLICY "series_read"      ON series      FOR SELECT TO authenticated USING (true);
CREATE POLICY "releases_read"    ON releases    FOR SELECT TO authenticated USING (true);
CREATE POLICY "sync_log_read"    ON sync_log    FOR SELECT TO authenticated USING (true);

-- Pulls: cada usuario solo ve y toca los suyos
CREATE POLICY "pulls_select" ON pulls FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "pulls_insert" ON pulls FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "pulls_update" ON pulls FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "pulls_delete" ON pulls FOR DELETE TO authenticated USING (auth.uid() = user_id);
